team_map = {"ARI" : [],
            "ATL" : ["MLN", "BSN"],
            "BAL" : ["SLB", "MLA"],
            "BOS" : [],
            "CHC" : [],
            "CHW" : [],
            "CIN" : [],
            "CLE": [],
            "COL": [],
            "DET": [],
            "HOU": [],
            "KCR": [],
            "LAA": ["ANA", "CAA", "CAL" ],
            "LAD": ["BRO"],
            "MIA": ["FLA"],
            "MIL": ["SEP"],
            "MIN": ["WSH"],
            "NYM": [],
            "NYY": [],
            "OAK": ["KCA", "PHA"],
            "PHI": [],
            "PIT": [],
            "SD": ["SDP"],
            "SF": ["SFG", "NYG"],
            "SEA": [],
            "STL": [],
            "TB": ["TBD", "TBR"],
            "TEX": ["WSA"],
            "TOR": [],
            "WAS" : ["WSN", "MON"]
            }

