team_map = {"ARI" : [],
            "ATL" : ["MLN", "BSN"],
            "BAL" : ["SLB", "MLA"],
            "BOS" : [],
            "CHC" : [],
            "CHW" : [],
            "CIN" : [],
            "CLE": [],
            "COL": [],
            "DET": [],
            "HOU": [],
            "KCR": [],
            "LAA": ["ANA", "CAA", "CAL" ],
            "LAD": ["BRO"],
            "FLA": ["MIA"],
            "MIL": ["SEP"],
            "MIN": ["WSH"],
            "NYM": [],
            "NYY": [],
            "OAK": ["KCA", "PHA"],
            "PHI": [],
            "PIT": [],
            "SDP": [],
            "SFG": ["NYG"],
            "SEA": [],
            "STL": [],
            "TBD": ["TBR"],
            "TEX": ["WSA"],
            "TOR": [],
            "WSN" : ["MON"]
            }

